sudo: required

language: R

services:
  - docker

before_install:
  - docker build -t benmarwick/guanyingdongstoneartefacts .
  - docker run -d -p 127.0.0.1:80:4567 benmarwick/guanyingdongstoneartefacts
  - docker ps -a

