---
output: html_document
---


Some normal text.



```{r warning=FALSE, message=FALSE}
# read in the data
library(dplyr)
library(knitr)
library(readxl)
library(fitdistrplus)
library(plyr)
library(ggplot2)
library(tidyr)
library(classInt)
# install.packages("readxl")
file_name <- "../data/artefacts (26_07_2016).xls" 
flakes <- read_excel(file_name, sheet = "flake basics")
cores <- read_excel(file_name, sheet = "core basics")
debris <- read_excel(file_name, sheet = "chunk&debris")
retouch <- read_excel(file_name, sheet = "retouch")

names(flakes) <- make.names(names(flakes))
names(cores) <- make.names(names(cores))
names(debris) <- make.names(names(debris))
names(retouch) <- make.names(names(retouch))
```

```{r}
# basic details of the dataset
artefact_ids <- list(flake_ids = flakes$number,
                     core_ids = cores$number,
                     debris_ids = debris$number,
                     retouch_ids = retouch$number)

retouch_ids <- retouch$number

# how many unique artefacts?
totals_of_each_type <- lapply(artefact_ids, function(i) length(unique(i)))
count_unique_artefacts <- sum(unlist(totals_of_each_type))
# debris pieces that are  retouch pieces
debris_with_retouch <- intersect(artefact_ids$retouch_ids, artefact_ids$debris_ids)
proportion_debris_retouched <- length(debris_with_retouch) / count_unique_artefacts 
# proportion of each type

type_table <- data.frame(type = names(as.data.frame(totals_of_each_type)),
                         count = as.numeric(as.data.frame(totals_of_each_type)),
                         proportion = round(as.numeric(prop.table(as.data.frame(totals_of_each_type))),3))
# add total row at the bottom
type_table$type <- as.character(type_table$type)
type_table <- rbind(type_table, c("total", count_unique_artefacts, round(sum(type_table$proportion),2)))
# print pretty table                         
kable(type_table) 
```


```{r}
# clean data to help with analysis
flakes$retouched <- ifelse(grepl("ret", flakes$type), "retouched", "unretouched")
flakes <- flakes[!flakes$material %in% c('qutz', 'quartz', 'basalt'),]

# how many levallois?
unique(flakes$type)
leva <- flakes %>% 
  filter(grepl("leva", type))
non_leva <- flakes %>% 
  filter(!grepl("leva", type))

flakes_L <-  
  mutate(flakes, L = ifelse(grepl("leva", type), "L", "N"))

# are the levallois pieces bigger?
ggplot(flakes_L, aes(x = L, 
                     y = mass)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.2) +
  scale_y_log10()

# is it significant?
t.test(data = flakes_L, mass ~ L)
# no


# explore variation in thickness in these groups
thick_plot <- ggplot(flakes_L) +
  geom_density(aes(`Thickness at 25% max dim`), colour = "red", alpha = 0.3) +
  geom_density(aes(`Thickness at 50% max dim`), colour = "green", alpha = 0.3) +
  geom_density(aes(`Thickness at 75% max dim`), colour = "blue", alpha = 0.3) +
  xlab("Thickness (mm)")

thick_plot

# strict leva

flakes_L <-  
  mutate(flakes_L, L_strict = ifelse(grepl("^leva$", type), "L_strict", "N"))

# are the levallois pieces bigger?
ggplot(flakes_L, aes(x = L_strict, 
                     y = mass)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.2) +
  scale_y_log10()

# is it significant?
t.test(data = flakes_L, mass ~ L_strict)
# no


# by size class that we identified earlier
thick_plot +
  facet_wrap(~ L_strict, ncol = 1)

# compare platform attributes, especially thickness
ggplot(flakes_L) +
  geom_density(aes(`platform thickness`)) +
  facet_wrap(~ L_strict, ncol = 1) +
  theme_bw()

# compare platform attributes, especially thickness
library(ggforce)
ggplot(flakes_L,
       aes(L_strict,
           `platform thickness`)) +
  geom_boxplot() +
  geom_sina(method = "counts",
            size = 2,
            alpha = 0.4) +
  theme_bw()



# need a test of uniformity (peak width)

# check the CVs
CV <- function(the_vector){
  mean_ <- mean(the_vector, na.rm = TRUE)
  sd_ <- sd(the_vector, na.rm = TRUE)
  cv <- (sd_/mean_) * 100
  round(cv, 3)
}


flakes_L %>% 
  group_by(L) %>% 
  dplyr::summarise(cv_25_thick = CV(`Thickness at 25% max dim`),
                   cv_50_thick = CV(`Thickness at 50% max dim`),
                   cv_75_thick = CV(`Thickness at 75% max dim`),
                   cv_25_width = CV(`Width at 25% max dim`), 
                   cv_50_width = CV(`Width at 50% max dim`),
                   cv_75_width = CV(`Width at 75% max dim`), 
                   n = n()) %>% View


```

 stop here


```{r}
# explore with some tables and plots



# function to compute frequencies and make a plot
f <-  function(the_data, the_column) {
  data.frame(table(the_data[the_column])) %>% 
    ggplot(aes(x = reorder(Var1, Freq), y = Freq)) +
    geom_bar(stat = "identity") +
    ylab("n") +
    xlab(the_column) + 
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
}

# some plots of frequencies
#f(flakes, "yuanfenlei")
f(flakes, "type")
f(flakes, "type2")
f(flakes, "retouched")
f(flakes, "material")

# mass for all flakes
ggplot(flakes, aes(mass)) +
  geom_histogram(binwidth = 10) 

ggplot(flakes, aes(mass)) +
  geom_density() +
  scale_x_log10()

ggplot(flakes, aes(length, `Width at 50% max dim`, colour = material)) +
  geom_point() +
  geom_smooth(method = "lm")

# mass for all flakes, retouched or not
ggplot(flakes, aes(mass, colour = retouched)) +
  geom_density()

# mass for all flakes, by raw material
ggplot(flakes, aes(mass, colour = material)) +
  geom_density()

# max dim for all flakes
ggplot(flakes, aes(`max dimension`)) +
  geom_histogram(binwidth = 2)

# max dim for all flakes, retouched or not 
ggplot(flakes, aes(`max dimension`, colour = retouched)) +
  geom_density()

# max dim for all flakes, by raw material
ggplot(flakes, aes(`max dimension`, colour = material)) +
  geom_density()

# scar counts for all flakes, by raw material
ggplot(flakes, aes(`scar number`)) +
  geom_histogram()

flakes$scar_group <- ifelse(flakes$`scar number` > 5, "more_than_5", "less_than_5")
ggplot(flakes, aes(mass, x = scar_group)) +
  geom_boxplot() +
  scale_y_log10()

# facetted plaforms
flakes$facetted_platform <- ifelse(grepl("fac", flakes$platform), "fac", "no")
ggplot(flakes, aes(`max dimension`, colour = facetted_platform)) +
  geom_density()
```

```{r}


# what distribution fits the data?
what <- as.numeric(na.omit(flakes$`max dimension`))
descdist(what, discrete = FALSE, boot = 500)
fit.gamma <- fitdist(what, "gamma")
plot(fit.gamma)
fit.gamma$aic # lower is better

```


```{r}
# Look to see if groups exist

# by flake size
plain_flakes <-  flakes[grepl("fl", flakes$type), ]
d <- density(na.omit(plain_flakes$mass)) # returns the density data
# plot
plot(d)
ggplot(plain_flakes, aes(mass)) +
  geom_density()

# test is we can discover natural breaks that divide up the flakes?

# how many groups should we look for?
n <- 2
natural_breaks <- classIntervals(plain_flakes$mass, n = n, 
                                 style = "jenks", dataPrecision = 2)
# plot the breaks
ggplot(plain_flakes, aes(mass)) +
  geom_density(colour = "blue") +
  geom_vline(xintercept = natural_breaks$brks, colour = "red")

# create a df
plain_flakes$mass_group <- cut(plain_flakes$mass, 
                               breaks = c(0, natural_breaks$brks[-1]),
                               labels = 1:(length(natural_breaks$brks)-1))
# remove flakes not in a group
plain_flakes <- plain_flakes[!is.na(plain_flakes$mass_group), ]

# plot the groups
ggplot(plain_flakes, aes(mass_group, mass)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.1) +
  theme_bw()
```

```{r}
# explore variation in thickness in these groups
thick_plot <- ggplot(plain_flakes) +
  geom_density(aes(`Thickness at 25% max dim`), colour = "red", alpha = 0.3) +
  geom_density(aes(`Thickness at 50% max dim`), colour = "green", alpha = 0.3) +
  geom_density(aes(`Thickness at 75% max dim`), colour = "blue", alpha = 0.3) +
  xlab("Thickness (mm)")

thick_plot

# by size class that we identified earlier
thick_plot +
  facet_wrap(~ mass_group, ncol = 1)

# Lycett and Eren found out the thickness is more evenly distributed and less variable across preferential Levallois flakes. So , let's get the CV values for thickness for each group
CV <- function(the_vector){
  mean_ <- mean(the_vector, na.rm = TRUE)
  sd_ <- sd(the_vector, na.rm = TRUE)
  cv <- (sd_/mean_)*100
  round(cv, 3)
}


plain_flakes %>% 
  group_by(mass_group) %>% 
  dplyr::summarise(cv_25_thick = CV(`Thickness at 25% max dim`),
                   cv_50_thick = CV(`Thickness at 50% max dim`),
                   cv_75_thick = CV(`Thickness at 75% max dim`),
                   cv_25_width = CV(`Width at 25% max dim`), 
                   cv_50_width = CV(`Width at 50% max dim`),
                   cv_75_width = CV(`Width at 75% max dim`), 
                   n = n()) %>% View


```


```{r}
# look at CV of metric variables by size groups

```